/// Flutter icons IconeServicos
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IconeServicos
///      fonts:
///       - asset: fonts/IconeServicos.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class IconeServicos {
  IconeServicos._();

  static const _kFontFam = 'IconeServicos';
  static const String? _kFontPkg = null;

  static const IconData brickwall_brick_svgrepo_com = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData xidorq01 = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cuidadoridosos = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData personaltrainer = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ajudante_de_mudanc_as = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData massagista = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cortador_de_grama = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instalador_de_piso = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData soldador = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
